# TA_V8/RAG_MCP/docker-compose.yml
version: '3.8'

services:
  rag-mcp-unified:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ta_v8_rag_mcp_unified
    command: uv run uvicorn unified_mcp_server:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app
      - UV_PYTHON_INSTALL_DIR=/app/.venv
      - PATH=/app/.venv/bin:$PATH
    env_file:
      - /etc/TA_V8/RAG_MCP/secrets.env
    ports:
      - "8005:8000"
    volumes:
      - .:/app
    networks:
      - ta_v8_default
    depends_on:
      - rag-agent-team

  rag-agent-team:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ta_v8_rag_agent_team
    command: uv run uvicorn rag_agent_team:app --host 0.0.0.0 --port 8001 --reload
    environment:
      - PYTHONPATH=/app
      - UV_PYTHON_INSTALL_DIR=/app/.venv
      - PATH=/app/.venv/bin:$PATH
    env_file:
      - /etc/TA_V8/RAG_MCP/secrets.env
    ports:
      - "8006:8001"
    volumes:
      - .:/app
    networks:
      - ta_v8_default

networks:
  ta_v8_default:
    external: true
    name: ta_v8_default
